name: CI - main workflow

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
    types: [ opened, synchronize ]

  workflow_dispatch:

jobs:
  linter:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      # runs install 
      - name: Run installation
        run: yarn install

      # runs lint
      - name: Run lint
        run: yarn lint
